version: '3'

services:
  
  app:
    build:
      context: .docker/app
      dockerfile: Dockerfile
    container_name: app
    tty: true
    restart: always
    volumes:
      - .docker/app/:/var/www
    networks:
      - creci-net  
    depends_on:
      - redis
      - nginx

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    tty: true
    expose:
      - 6379
    networks:
      - creci-net
    depends_on:
      - nginx

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .docker/app/:/var/www
    networks:
      - creci-net

networks:
  creci-net:
    driver: bridge